version: '3'

services:
  teigarage:
    image: teic/teigarage
    container_name: teigarage
    volumes:
      - /data2/Vault/Stylesheets/current/xml/tei/stylesheet:/usr/share/xml/tei/stylesheet:ro
      - /data2/Vault/P5/current/xml/tei/odd:/usr/share/xml/tei/odd:ro
    environment:
      - WEBSERVICE_URL=https://teigarage.tei-c.org/ege-webservice/
      - VIRTUAL_HOST=teigarage.tei-c.org
      - LETSENCRYPT_HOST=teigarage.tei-c.org
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped
    labels:
      autoheal: true

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: teigarage-autoheal
    network_mode: none
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

networks:
  default:
    external:
      name: tei_net
