services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.11-alpine
    container_name: nginx-proxy
    networks:
      - tei
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-html:/usr/share/nginx/html
    configs:
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/teigarage.tei-c.org
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/oxgarage.tei-c.org
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/roma.tei-c.org

    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    networks:
      - tei
    environment:
      - DEFAULT_EMAIL=stadler@edirom.de
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-certs:/etc/nginx/certs
      - nginx-proxy-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    network_mode: none
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

volumes:
  nginx-proxy-certs:
  nginx-proxy-html:
  acme:

networks:
  tei:
    name: tei_net

configs:
  nginx_additional_conf:
    content: client_max_body_size 150m;
