version: '3'

services:
  ojs:
    image: stadlerpeter/docker-pkp-ojs:3.2.0
    container_name: ojs
    volumes:
      - /data/lib/ojsfiles:/var/www/html/files
      - /data/lib/ojspublic:/var/www/html/public
    environment:
      - PKP_DATABASE_DRIVER=mysqli
      - PKP_DATABASE_HOST=ojsdb
      - PKP_DATABASE_USERNAME=jtei_ojs3-test
      - PKP_DATABASE_NAME=jtei_ojs3-test
      - PKP_DATABASE_PASSWORD=
      - PKP_GENERAL_INSTALLED=yes
      - PKP_GENERAL_BASE_URL=https://journal.tei-c.de
      - HACK_BASE_URL=true
      - VIRTUAL_HOST=journal.tei-c.de
      - LETSENCRYPT_HOST=journal.tei-c.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped

  ojsdb:
    image: mariadb:10
    container_name: ojsdb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/lib/ojsdb:/var/lib/mysql
      - /data/tmp:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped

networks:
  default:
    external:
      name: tei_net

