services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7-alpine
    container_name: nginx-proxy
    networks:
      tei_net:
        # pin the container to a fixed ip address
        # so downstream containers can set that address as trusted proxy
        ipv4_address: 172.20.0.2
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-html:/usr/share/nginx/html
    configs:
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/teigarage.tei-c.org
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/oxgarage.tei-c.org
      - source: nginx_additional_conf
        target: /etc/nginx/vhost.d/roma.tei-c.org

    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    networks:
      - tei_net
    environment:
      - DEFAULT_EMAIL=stadler@edirom.de
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-certs:/etc/nginx/certs
      - nginx-proxy-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    network_mode: none
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=1800
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DISABLE_CONTAINERS=watchtower

volumes:
  nginx-proxy-certs:
  nginx-proxy-html:
  acme:

networks:
  tei_net:
    name: tei_net
    ipam:
      config:
        # set a fixed subnet for the tei network
        - subnet: "172.20.0.0/24"

configs:
  nginx_additional_conf:
    content: client_max_body_size 150m;
