version: '3'

services:
  vault:
    image: nginx:alpine
    container_name: vault
    volumes:
      - /data2/web/tei-c.dhinstitute.ca/public_html/Vault:/usr/share/nginx/html:ro
      - /etc/nginx/vault.tei-c.org.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=vault.tei-c.org
      - LETSENCRYPT_HOST=vault.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped

networks:
  default:
    external:
      name: tei_net
