version: '3'

services:
  roma:
    image: teic/roma
    container_name: romaantiqua
    volumes:
      - /data2/Vault/P5/current/xml/tei/custom:/usr/share/xml/tei/custom:ro
    environment:
      - OXGARAGE_SERVER=https://oxgarage-humanum.tei-c.org/ege-webservice
      - ROMA_XQUERY_SERVER=http://xquery4roma:8080/Query/
      - ROMA_TEIWEB_SERVER=https://tei-c.org/release/doc/tei-p5-doc/
      - VIRTUAL_HOST=romaantiqua.tei-c.org
      - LETSENCRYPT_HOST=romaantiqua.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped

  xquery4roma:
    image: teic/xquery4roma
    container_name: xquery4roma
    environment:
      - P5SUBSET_URL=https://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml
    restart: unless-stopped

networks:
  default:
    external:
      name: tei_net

