name: debian-packages

services:
  debian-packages:
    image: nginx:alpine
    container_name: debian-packages
    volumes:
      - /data/TEI-apt-repo:/usr/share/nginx/html/deb:ro
    environment:
      - VIRTUAL_HOST=packages.tei-c.org
      - LETSENCRYPT_HOST=packages.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped

networks:
  tei_net:
    external: true
