version: '3.7'

services:
  ojs:
    image: teic/docker-pkp-ojs:3.5.0
    container_name: ojs
    volumes:
      - /data/docker-volumes/ojsfiles:/var/www/html/files
      - /data/docker-volumes/ojspublic:/var/www/html/public
    environment:
      - PKP_DATABASE_DRIVER=mysqli
      - PKP_DATABASE_HOST=ojsdb
      - PKP_DATABASE_CONNECTION_CHARSET=utf8mb4
      - PKP_DATABASE_COLLATION=utf8mb4_unicode_ci
      - PKP_I18N_LOCALE=en
      - PKP_I18N_CONNECTION_CHARSET=utf8mb4
      - PKP_GENERAL_INSTALLED=On
      - PKP_GENERAL_BASE_URL=https://journal.tei-c.org
      - PKP_EMAIL_DEFAULT=smtp
      - PKP_EMAIL_SMTP=On
      - PKP_EMAIL_SMTP_SERVER=relay.huma-num.fr
      - PKP_EMAIL_SMTP_PORT=25
      - PKP_EMAIL_REQUIRE_VALIDATION=On
      - PKP_EMAIL_FORCE_DMARC_COMPLIANT_FROM=On
      - PKP_EMAIL_DMARC_COMPLIANT_FROM_DISPLAYNAME='%n via %s'
      - PKP_EMAIL_ALLOW_ENVELOPE_SENDER=On
      - PKP_EMAIL_FORCE_DEFAULT_ENVELOPE_SENDER=On
      - PKP_EMAIL_DEFAULT_ENVELOPE_SENDER=journal@tei-c.org
      - PKP_CAPTCHA_RECAPTCHA=On
      - PKP_CAPTCHA_ON_REGISTER=On
      - PKP_GENERAL_SCHEDULED_TASKS=On
      - PKP_GENERAL_SANDBOX=Off
      - PKP_GENERAL_ALLOWED_HOSTS='["journal.tei-c.org"]'
      - PKP_INVITATIONS_EXPIRATION_DAYS=14
      - PKP_SECURITY_ALLOWED_HTML="a[href|target|title],em,strong,cite,code,ul,ol,li[class],dl,dt,dd,b,i,u,img[src|alt],sup,sub,br,p"
      - VIRTUAL_HOST=journal.tei-c.org
      - LETSENCRYPT_HOST=journal.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped
    secrets:
      - source: db_passwd
        target: PKP_DATABASE_PASSWORD
      - source: db_username
        target: PKP_DATABASE_USERNAME
      - source: db_name
        target: PKP_DATABASE_NAME
      - source: ojs_recaptcha_private_key
        target: PKP_CAPTCHA_RECAPTCHA_PRIVATE_KEY
      - source: ojs_recaptcha_public_key
        target: PKP_CAPTCHA_RECAPTCHA_PUBLIC_KEY
      - source: ojs_salt
        target: PKP_SECURITY_SALT
      - source: ojs_appkey
        target: PKP_GENERAL_APP_KEY      

  ojsdb:
    image: mariadb:10
    container_name: ojsdb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/docker-volumes/ojsdb:/var/lib/mysql
      - /data/tmp:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER_FILE=/run/secrets/db_username
      - MYSQL_DATABASE_FILE=/run/secrets/db_name
      - MYSQL_PASSWORD_FILE=/run/secrets/db_passwd
    restart: unless-stopped
    secrets:
      - source: db_passwd
      - source: db_username
      - source: db_name

networks:
  default:
    external:
      name: tei_net

secrets:
  db_passwd:
    file: /data/docker-secrets/ojs-db-password
  db_username:
    file: /data/docker-secrets/ojs-db-username
  db_name:
    file: /data/docker-secrets/ojs-db-name
  ojs_recaptcha_private_key:
    file: /data/docker-secrets/ojs-recaptcha-private-key
  ojs_recaptcha_public_key:
    file: /data/docker-secrets/ojs-recaptcha-public-key
  ojs_salt:
    file: /data/docker-secrets/ojs-salt
  ojs_appkey:
    file: /data/docker-secrets/ojs-appkey