version: '3'

services:
  oxgarage:
    image: teic/oxgarage
    container_name: oxgarage
    volumes:
      - /data2/Vault/Stylesheets/current/xml/tei/stylesheet:/usr/share/xml/tei/stylesheet:ro
      - /data2/Vault/P5/current/xml/tei/odd:/usr/share/xml/tei/odd:ro
    environment:
      - WEBSERVICE_URL=https://oxgarage-humanum.tei-c.org/ege-webservice/
      - VIRTUAL_HOST=oxgarage-humanum.tei-c.org,oxgarage.tei-c.org,teigarage.tei-c.org
      - LETSENCRYPT_HOST=oxgarage-humanum.tei-c.org,oxgarage.tei-c.org,teigarage.tei-c.org
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped

networks:
  default:
    external:
      name: tei_net
