name: teiwebsite

services:
  website:
    image: teic/website:dockerize
    container_name: website
    volumes:
      - /data/Vault/P5/current:/usr/local/apache2/htdocs/release:ro
      - /data/Vault:/usr/local/apache2/htdocs/Vault:ro
    environment:
      - VIRTUAL_HOST=tei-c.org,www.tei-c.org
      - LETSENCRYPT_HOST=tei-c.org,www.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped
    networks:
      - tei_net
    labels:
      autoheal: "true"

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: teiwebsite-autoheal
    network_mode: none
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

networks:
  tei_net:
    external: true
