name: roma

services:
  romabeta:
    image: teic/romajs
    container_name: roma
    environment:
      - OXGARAGE_LOCATION=teigarage.tei-c.org
      - OXGARAGE_PROTOCOL=https
      - VIRTUAL_HOST=roma-humanum.tei-c.org,romabeta.tei-c.org,roma.tei-c.org
      - LETSENCRYPT_HOST=roma-humanum.tei-c.org,romabeta.tei-c.org,roma.tei-c.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=stadler@edirom.de
    restart: unless-stopped
    networks:
      - tei_net

networks:
  tei_net:
    external: true
