version: '3.5'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7-alpine
    container_name: nginx-proxy
    networks:
      - tei
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /data/docker-volumes/proxy-max-body-size.conf:/etc/nginx/conf.d/proxy-max-body-size.conf:ro
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-html:/usr/share/nginx/html
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    networks:
      - tei
    environment:
      - DEFAULT_EMAIL=stadler@edirom.de
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-certs:/etc/nginx/certs
      - nginx-proxy-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    restart: unless-stopped

volumes:
  nginx-proxy-certs:
  nginx-proxy-html:
  acme:

networks:
  tei:
    name: tei_net
